In [30]:
import math
import pandas as pd
import numpy as np

## Função de ativação

In [31]:
def sigmoidal(pre_y):
    maior = 0
    pos = 0
    y = [0,0,0]
    for i,x in enumerate(pre_y):
        if x >= 0:
            parte_exp = math.exp(-x)
            sig = 1 / (1 + parte_exp)
        else:
            parte_exp = math.exp(x)
            sig = parte_exp / (1 + parte_exp)
        if sig >= maior:
            maior = sig
            pos = i
    
    y[pos] = 1
    
    return y
        
            
    
def degrau(pre_y):
    y = []
    for x in pre_y:
        if x >= 0:
            y.append(1)
        else:
            y.append(0)
    return y

## Perceptron e Teste de precisão

In [62]:
# perceptron ----------------------------------------TERMINAR
def perceptron (max_it, taxa_aprendizagem, X, D, funcao_ativacao):
    W = np.array([[0,0,0,0],
                [0,0,0,0],
                [0,0,0,0]])
    b = np.array([0,0,0])
    iter_count: int = 1
    E = 1
    while (iter_count < max_it and E>0):
        E = 0
        for i,x in X.iterrows():
            y = funcao_ativacao(np.matmul(W, np.array(x.array)) + b)
            erro = np.array(D[i]) - np.array(y)
            b = b + taxa_aprendizagem*erro
            W = W + taxa_aprendizagem*(np.outer(erro,x.array))
            E = E + erro.dot(erro)
        iter_count = iter_count + 1
    
    return (W,b)

# Acuracia
def testa_acuracia (X, D, W, b, funcao_ativacao):
    acertos = 0
    for i,x in X.iterrows():
        Y = funcao_ativacao(W.dot(np.array(x.array)) + b)
        erro = np.array(D[i]) - np.array(Y)
        
        if all (valor == 0 for valor in erro):
            acertos = acertos + 1
    taxa_acertos = 100*(acertos/len(X))
    return (acertos, taxa_acertos)


## Dataset

In [63]:
# Perceptron

# Ler do dataset
dataset = pd.read_table("iris.data", sep=",",header=None)
dataset.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'Classe']

# Bag of class
dict_class = {
    'Iris-setosa':[1,0,0],
    'Iris-versicolor': [0,1,0],
    'Iris-virginica': [0,0,1]
}

dataset["D"] = dataset["Classe"].apply(lambda x: dict_class[x])

dataset

sepal length  sepal width  petal length  petal width          Classe  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

             D  
0    [1, 0, 0]  
1    [1, 0, 0]  
2    [1, 0, 0]  
3    [1, 0, 0]  
4    [1, 0, 0]  
..         ...  
145  [0, 0, 1]  
146  [0, 0, 1]  
147  [0, 0, 1]  
148  [0, 0, 1]  
149  [0, 0, 1]  

[150 rows x 6 columns]

## Testes

In [72]:
X = dataset.drop(["Classe","D"], axis= 1)
D = dataset["D"]
taxa_aprendizagem = 0.4
max_iter = 300

(W,b) = perceptron(max_iter, taxa_aprendizagem, X, D, degrau)
print(W)
print(b)

[[ 0.11  0.36 -0.52 -0.22]
 [ 6.04 -6.99 -1.19 -8.71]
 [-7.86 -6.96 10.65 13.21]]
[ 0.1 -3.9 -3.6]


In [73]:
testa_acuracia(X,D,W,b, degrau)

(90, 60.0)